version: "3.7"
services:
  nextjs:
    container_name: nextJs
    image: "node:18"
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
  nginx:
    build: ./docker/nginx
    links:
      - nextjs
    ports:
      - "80:80"